micronaut:
  application:
    name: test-transactional-service
jackson:
  module-scan: false
datasources:
  default:
    url: "jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password: ""
    driverClassName: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
  second:
    url: "jdbc:h2:mem:ora;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password: ""
    driverClassName: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
  second:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
